mash-up-kr/DHC-Android

app/build.gradle.kts, config/detekt/detekt.yml, gradle/libs.versions.toml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/19
- detekt 의존성 추가
- detekt-formatting 의존성 추가 (trailing comma 에 대한 탐지 기능 추가를 위해서 넣었습니다)
- detekt.yml 파일은 자동생성된 파일에 개인취향을 담아서 조금 일부 rule 들을 추가하였습니다. 하나하나 다 코딩한 것이 아님을 공유드립니다.
- 커스텀된 ruleset 목록
- NamedArguments : threshold 이상이면 NamedArguments 꼭 사용하기 
- AlsoCouldBeApply : also 대신 apply 사용해도 될 것 같으면 apply 사용하라고 알려주기
- CanBeNonNullable : nullable 인데 null 안해도 될 것 같으면 탐지하는 기능
- SpacingBetweenPackageAndImports : package 랑 Import 사이에 공백 넣었는지 탐지
- UnusedImports : 미사용 import 탐지 기능
- DataClassShouldBeImmutable : data class 사용하면 property 가 불변이여야한다는 의미
과도한 세팅이라고 느껴진다면 공유 부탁드립니다.
(우선 이렇게 해두고 추후 하다가 개발에 지장을 줄 정도로 과도하면 지울 생각이긴 합니다)
` ./gradlew detekt` 을 통해 구현할 수 있습니다.
close #19
=> [#19] detekt 의존성 및 ruleset 추가

.github/workflows/build-debug-check.yaml, .github/workflows/build-release-check.yaml, presentation/sample/src/main/java/com/dhc/sample/home/HomeScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/44
- 빌드 잘 되는지 테스트하는 깃헙 액션 만들기
- gitflow 정책에 기반하여 `develop` 으로 향하는 PR 은 debug build 테스트를 하고, `release/*`, `main` 으로 향하는 PR 은 release build 테스트를 하도록 구현하였습니다.
|빌드 실패|빌드 성공|  
|:---|---|
|![image](https://github.com/user-attachments/assets/38855c83-f71e-4409-8248-7333fa3f8594)|![image](https://github.com/user-attachments/assets/8d04f43d-a144-498d-8ee5-e4dbf7a589d0)|
시연이미지는 둘  다 동작하는거 보려고 release, debug action 이 모두 돌아가게 의도적으로 세팅했었습니다.
close #44
=> [#44] PR 단계에서 빌드 정상동작 테스트하는 github action 제작 

gradle/libs.versions.toml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/55
- Kotlin Version upgrade (2.0.0 -> 2.0.21)
- 사유 : 2.0.20 버전부터 strong skipping mode 가 기본적으로 사용되어, immutableList 를 사용하지 않아도 List parameter 에서 recomposition 되는 이슈를 방지한다고 공지되어있기 때문
- ref : https://developer.android.com/develop/ui/compose/performance/stability/strongskipping?hl=ko#enable-strong
- 이대로 사용해보고 List parameter 넘겼는데 recomposition 발생하면 다시 고민해보자
-
close #55
=> [#55]  Kotlin Version upgrade (2.0.0 -> 2.0.21)

data/build.gradle.kts, data/src/main/kotlin/com/dhc/dhcandroid/datastore/PreferencesName.kt, data/src/main/kotlin/com/dhc/dhcandroid/datastore/PreferencesSerializer.kt, data/src/main/kotlin/com/dhc/dhcandroid/datastore/SamplePreferencesSerializer.kt, data/src/main/kotlin/com/dhc/dhcandroid/di/DatastoreModule.kt, data/src/main/proto/sample_preferences.proto, gradle/libs.versions.toml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/50
- proto datastore 의존성 추가
- Serializer 및 Datastore 파일 생성 샘플코드 작성 
- 찡끗
- 빌드성공 확인하였습니다.
close #50
=> [#50] Proto Datastore 의존성 추가 및 Sample 코드 작성

app/build.gradle.kts, app/src/main/java/com/dhc/dhcandroid/MainActivity.kt, config/detekt/detekt.yml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/63
- detekt 자동으로 포매팅 하는 옵션 추가하였습니다.
- LongMethod (하나의 함수가 가질 수 있는 최대 길이에 대한 Lint 조건) 이 현재 60줄이고, 이거 너무 타이트해보여서 150줄로 수정하였습니다!
- 혹시 더 수정하고 싶은 규칙 있으면 알려주세용
- 자동포매팅은 따로 옵션 줄건 없고, `./gradlew detekt` 실행하면 자동으로 수정됩니당~ 
- 근데 다 고칠 수 있는거만 고쳐주는거라서 전부다 수정해주진 않으니 참고해주세용 (예를들어 트레일링 콤마는 자동으로 달아주고, 공백같은건 자동으로 제거해줌) 
close #63
=> [#63] detekt 자동포매팅 적용

core/designsystem/src/main/kotlin/com/dhc/designsystem/Typography.kt, core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/DhcFortuneCard.kt, core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/FlippableBox.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/113
- 뒤집기 가능한 FlippableBox 와 카드 디자인의 DhcFortuneCard 를 개발해봤어용
- 드래그로 뒤집기도 가능하고, 클릭으로 뒤집기도 가능해요
- 뒤집고나면 되돌릴 수 없어용
- 이것저것 지원 가능하게 파라미터를 넣긴 했는데, 필요한거 더 보이면 공유해주시면 개발할게용
|기능 구현|  
|---|
|<video src="https://github.com/user-attachments/assets/7dc354b1-b57e-40a9-acd5-7f9671bd3a15"/>|

close #113
=> [#113] FlippableBox, DhcFortuneCard 추가

core/designsystem/src/main/kotlin/com/dhc/designsystem/FortuneCore.kt, core/designsystem/src/main/kotlin/com/dhc/designsystem/MoreButton.kt, core/designsystem/src/main/res/values/strings.xml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/133
- 금전운 코어와 더보기 버튼 구현완료~!
(짧아서 같이 올립니다..)
- 근데 둘다 홈화면에서만 사용해서... 홈모듈 머지후에 옮기려고 하는데 어때요??
- 금전운 코어는 뒤에 배경 투명이었음....!
|:---|---|
|<img width="197" alt="스크린샷 2025-06-13 오후 4 14 07" src="https://github.com/user-attachments/assets/9c3c89e9-74ca-4762-ba28-420d010dccba" />|<img width="355" alt="스크린샷 2025-06-13 오후 4 14 28" src="https://github.com/user-attachments/assets/48ede291-65da-4844-91d3-ad708f7fb174" />|
close #133
=> [#133] 디자인 시스템 컴포넌트 - 금전운 점수, 더보기 버튼

core/designsystem/src/main/kotlin/com/dhc/designsystem/title/DhcTitle.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/168
- DhcTitle 정렬기능 사용하면 내부 텍스트의 가로범위 때문에 의도와 다르게 노출되는 이슈가 있슴당
- ㅠㅠ
|---|---|
|<img width="233" alt="스크린샷 2025-06-15 오후 5 36 44" src="https://github.com/user-attachments/assets/2a2a0bae-29c7-48aa-83a9-7357c12e5295" />|<img width="241" alt="스크린샷 2025-06-15 오후 5 35 52" src="https://github.com/user-attachments/assets/c11fb552-77fc-480c-8727-d1d377fbe88e" />|
close #168
=> [#168] DhcTitle subtitle 과 title 의 가로범위가 동일하지 않은 이슈 수정

app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt, core/presentation/src/main/java/com/dhc/presentation/component/MissionTitle.kt, presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionContract.kt, presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionRoute.kt, presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionScreen.kt, presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionViewModel.kt, presentation/intro/src/main/res/values/strings.xml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/162
- 인트로화면의 미션확인 화면 구현하였습니다.
- 미션확인 화면에 있는 내용들은 모두 하드코딩 되어있습니다.
- 시연화면 보면 미션아이템이 figma 디자인과 쪼매 다른데, 이게 디자인시스템이 바뀐게 반영이 안되어서 그런지 디자인시스템 컬러 자체가 잘못 들어가 있더라구용.. 요건 별도 PR 로 수정하겠습니당  
|기능 구현|  
|---|
|<video src="https://github.com/user-attachments/assets/747dc548-ad5d-4458-9e61-412061593515"/>|
close #162
=> [#162] 인트로화면 - 미션확인

app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt, core/common/src/main/java/com/dhc/common/CalendarUtil.kt, core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/FlippableBox.kt, core/designsystem/src/main/kotlin/com/dhc/designsystem/score/DhcScoreText.kt, core/presentation/src/main/java/com/dhc/presentation/component/MissionTitle.kt, presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardContract.kt, presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardRoute.kt, presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardScreen.kt, presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardViewModel.kt, presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionContract.kt, presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionRoute.kt, presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionScreen.kt, presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionViewModel.kt, presentation/intro/src/main/res/values/strings.xml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/160 
- 인트로화면의 금전운 카드 뒤집기 화면을 구현했습니다.
- 카드에 대한 상세 디자인에 맞추어서 추가 개발될 예정입니당
- 찡끗
|기능 구현|  
|---|
|<video src="https://github.com/user-attachments/assets/93e5a8eb-8aff-4c48-a8fc-2282a52d5f2f"/>|
close #160
=> [#160] 인트로 화면 - 운세카드 화면

presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/204
- 54.dp 가 대충 디바이스 탑바 크기에 맞춘건데, 탑바사이즈는 기기별로 달라서 모든 기기에 대응될 수 있도록 기기의 탑바를 가져와서 offset 을 적용하는 것으로 수정했습니다
- 찡끗
close #204
=> [#204] 홈 TopBar 쪽 Gradient offset Topbar 크기 하드코딩하지 않도록 수정

data/src/main/kotlin/com/dhc/dhcandroid/model/MissionCategoriesResponse.kt, data/src/main/kotlin/com/dhc/dhcandroid/service/DhcService.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/244
- mission category 가져오는 API 랑 데이터모델 추가했어용
- 찡끗
close #244
=> [#244] 카테고리 정보 가져오기 Api 및 data model 추가

app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt, core/common/src/main/kotlin/com/dhc/common/DhcResult.kt, data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSource.kt, data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSourceImpl.kt, data/src/main/kotlin/com/dhc/dhcandroid/model/MissionCategoriesResponse.kt, data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt, data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt, data/src/main/kotlin/com/dhc/dhcandroid/service/DhcService.kt, presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryScreen.kt, presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryViewModel.kt, presentation/intro/src/main/java/com/dhc/intro/category/model/CategoryItem.kt, presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/246
- 서버에서 가져와서 보여주도록 구현해보았어용
- 히히
|기능 구현|  
|---|
|<img width="262" alt="스크린샷 2025-06-28 오후 10 54 22" src="https://github.com/user-attachments/assets/cd9c57f7-4b9c-422f-9cf9-ed7d69aade01" />|
close #246
=> [#246] 인트로 카테고리 정보 서버에서 받아오도록 수정

data/src/main/kotlin/com/dhc/dhcandroid/model/MyPageResponse.kt, presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageContract.kt, presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt, presentation/mypage/src/main/kotlin/com/dhc/mypage/model/MissionCategoryUiModel.kt, presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/MyPageScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/259
- 마이페이지 카테고리 서버 데이터 가져와서 연동했어요
|카테고리|  
|---|
|<img width="436" alt="image" src="https://github.com/user-attachments/assets/ca1cb8dc-8937-489b-8dde-5fa4e517cb00" />|
close #259
=> [#259] Feature : 마이페이지 카테고리 서버 데이터 연동

core/designsystem/src/main/kotlin/com/dhc/designsystem/mission/DhcCardReRoll.kt, data/src/main/kotlin/com/dhc/dhcandroid/model/HomeViewResponse.kt, presentation/home/src/main/java/com/dhc/home/HomeViewModel.kt, presentation/home/src/main/java/com/dhc/home/main/HomeContract.kt, presentation/home/src/main/java/com/dhc/home/main/HomeMissionComponent.kt, presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt, presentation/home/src/main/java/com/dhc/home/main/MissionChange.kt, presentation/home/src/main/java/com/dhc/home/model/HomeUiModel.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/310
- 홈 API에 오늘 미션끝냈는지 "todayDone" 추가 -> 플로팅 버튼 노출 조건 수정
- 미션 체크되거나 오늘 미션끝냈을 때 리롤 안되도록 조건 추가
- 돔황챠,,,처차차차차
|체크ON/OFF|오늘 미션 끝냈을 때|  
|:---|---|
|<video src="https://github.com/user-attachments/assets/e6913b0a-b0cf-4eaa-8cec-b7cbdb35654e">|<video src ="https://github.com/user-attachments/assets/6a80b97b-084b-47ee-b01a-a7649874f99b">|
close #310 
close #288
=> [#310] 오늘 미션 끝내기 여부 API 파라미터 추가 및 미션 완료 시 리롤 안되도록

core/designsystem/src/main/kotlin/com/dhc/designsystem/topbar/DhcBasicTopBar.kt, core/designsystem/src/main/res/drawable/ico_chevron_left.xml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/336
- 뒤로가기 버튼 추가 및 적용
편-안
|Before|After|
|-|-|
|<img width="419" height="938" alt="Image" src="https://github.com/user-attachments/assets/38f9a73e-91b5-4980-a415-4be459d603ba" />|<img width="419" height="934" alt="Image" src="https://github.com/user-attachments/assets/89ae0dfc-4033-47e4-96bf-bb6544e29129" />|
close #336
=> [#336] 인트로쪽 뒤로가기 버튼 아이콘 변경

app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt, presentation/intro/src/main/java/com/dhc/intro/start/IntroStartScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/319
- 애니메이션 때문에 다음으로 넘어갔다가 뒤로 바로 돌아오면 기존 Screen 을 재사용하는 것 같음.
- 근데 다음으로 누를 때 동영상 안보이게 state 처리 하였는데, 다음 누르고 바로 뒤로가기로 돌아와서 재사용하니까 동영상이 안보이는채로 멈추는 이슈가 발생함
- 그래서 그냥 애니메이션 읎애버림...
- navigation 골치아픈거 많네,,
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/6e44205c-41f4-43ef-b7ad-cfb29c9ef85a"/>|<video src="https://github.com/user-attachments/assets/092812d8-49b5-4a3c-86b9-edb3ce30f22d"/>|
close #319
=> [#319] 인트로 시작화면에서 다음으로 넘어갔다가 바로 뒤로가기로 되돌아오면 동영상 안보이는 이슈 수정

core/designsystem/src/main/kotlin/com/dhc/designsystem/gnb/DhcBottomBar.kt, core/designsystem/src/main/kotlin/com/dhc/designsystem/topbar/DhcTopBar.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/294
- 상단바랑 바텀바 자연스럽게 나타나고 사라질 수 있또록 처리
- 음음 좋아
|기능 구현|  
|---|
|<video src="https://github.com/user-attachments/assets/fbec038d-4b5c-4cff-b008-aac50f247bb6"/>|
close #294
=> [#294] TopBar 랑 BottomBar 에 대해서 생겨나고 사라질 때 애니메이션 적용하기

core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/DhcTipCardGrid.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/357
- 운세상세의 팁 카드 양쪽 높이값이 다르면 동일하게 맞도록 변경
- 흠
|---|---|
|<img width="236" alt="스크린샷 2025-07-07 오후 10 16 02" src="https://github.com/user-attachments/assets/a29cacdd-0c90-4213-ba1a-a58591adf02f" />|<img width="239" alt="스크린샷 2025-07-07 오후 10 19 21" src="https://github.com/user-attachments/assets/62c78ffc-0528-495c-b970-b6e5eb2f338a" />|
close #357
=> [#357] 운세상세의 팁 카드 양쪽 높이값이 다르면 동일하게 맞도록 변경

app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt, presentation/home/src/main/java/com/dhc/home/HomeRoute.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/324
- 홈화면 다른 탭 이동 시 상태 초기화 되는 이슈 수정하였슴당~!
- 아자자.
|:---|---|
|||
close #324
=> [#324] 홈화면 다른 탭 이동 시 상태 초기화 되는 이슈 수정

presentation/intro/src/main/java/com/dhc/intro/fortunedetail/IntroFortuneDetailViewModel.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/378
- o 안보이게 처리 필요한거 null 처리해야함
- 흠
|---|---|
|<img width="225" src="https://github.com/user-attachments/assets/004957d7-cd18-4a71-bbb8-f38650a08fa9"/>|<img width="225" alt="스크린샷 2025-07-10 오전 12 41 29" src="https://github.com/user-attachments/assets/f5745f05-1586-49d6-a7a6-3ed8f8bb72f1" />|
close #378
=> [#378] Intro 운세상세 color 안보여줘야 하는 부분 null 처리

core/presentation/src/main/java/com/dhc/presentation/component/VideoView.kt, presentation/intro/src/main/java/com/dhc/intro/start/IntroStartRoute.kt, presentation/intro/src/main/java/com/dhc/intro/start/IntroStartScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/377
- 인트로 시작화면 동영상 실행될때 바탕화면 나갔다오면 영상 꺼짐 이슈
- exoplayer 를 background 로 나가서 release() 시켰던 것 다시 데려와서 보여주려고 하다보니 생긴 오류인 것 같음
- state 로 만들고, Foreground 로 올라올 때 마다 다시 초기화하도록 하여 해결하였슴다
- 아따 영상 어렵네,,,
|Before|AFter|  
|---|---|
|<video src="https://github.com/user-attachments/assets/e3670d40-8cdd-4997-a7da-e0c7e939a25e"/>|<video src="https://github.com/user-attachments/assets/1cd4173c-6243-453c-b3a4-8538d9f28b16"/>|
close #377
=> [#377] 인트로 시작화면 동영상 실행될때 바탕화면 나갔다오면 영상 꺼짐 이슈

core/designsystem/src/main/kotlin/com/dhc/designsystem/snackbar/DhcSnackBar.kt, core/designsystem/src/main/kotlin/com/dhc/designsystem/snackbar/SnackBarUtil.kt, presentation/home/src/main/java/com/dhc/home/HomeRoute.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/320
- 토스트가 취소되고 다음꺼가 바로떠요~!
|기능A 구현|  
|:---|
|https://github.com/user-attachments/assets/ed49a9d8-5bc5-4813-bff5-777a8725dfb5|
close #320
=> [#320] 토스트 이전꺼 취소하고 뜨도록 수정

core/common/src/main/kotlin/com/dhc/common/StringExt.kt, core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/DhcTipCard.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/412
- color 값이 반 문자열이어도 null 과 동일하게 동작하게 수정
- color 값이 "" 이서서 파싱안된다는 오류 뜬거였음
-
|기능 구현|  
|---|
|<video src="https://github.com/user-attachments/assets/c18934fb-219a-4bf6-9648-b9f7692868e3"/>|
close #412
=> [#412] 미션상세 이동 시 크래시나는 현상 수정

presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/settinglist/SettingList.kt, presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/settinglist/SettingNormalItem.kt, presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/settinglist/SettingToggleItem.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/422 
- 리플영역 수정했슴당
- 그냥 Modifier 를 바깥으로 다 빼버렸어용
- 이미지 20.dp 로 고정값도 추가해줬어용
- 흠
|---|---|
|<video src="https://github.com/user-attachments/assets/68d02dca-a463-406f-9103-b5867ee8e4bc"/>|<video src="https://github.com/user-attachments/assets/cc2258c3-9eb1-40ad-9c0d-294141065363"/>|
close #422
=> [#422] 앱 초기화버튼 리플영역 수정

core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/DhcFortuneCard.kt, presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/429
- 홈화면 - 카드 텍스트, 이미지 겹치는 현상 수정
|After|
|---|
|<img width="439" height="904" alt="image" src="https://github.com/user-attachments/assets/c143d40b-0712-433f-b395-e5c16fa513bd" />|
close #429
=> [#429] 홈화면 - 카드 텍스트, 이미지 겹치는 현상 수정

core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/DhcTipCardGrid.kt, data/src/main/kotlin/com/dhc/dhcandroid/model/DailyFortuneResponse.kt, data/src/main/kotlin/com/dhc/dhcandroid/model/FortuneResponse.kt, presentation/home/src/main/java/com/dhc/home/detail/utils/Extensions.kt, presentation/home/src/main/java/com/dhc/home/model/TodayDailyFortuneUiModel.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/433
- 변경된 데이터 모델 반영
|금전운 상세 보기|
|---|
|<img width="391" height="800" alt="image" src="https://github.com/user-attachments/assets/0aafb448-4222-4b77-b81c-ed75b119236c" />|
close #433
=> [#433] 금전운 상세보기 데이터 비어 있는 현상 수정

core/designsystem/src/main/kotlin/com/dhc/designsystem/mission/MoneyFortuneMissionCard.kt, core/designsystem/src/main/kotlin/com/dhc/designsystem/mission/SpendingHabitMissionCard.kt, data/src/debug/assets/mock_home_view_response.json, presentation/home/src/main/java/com/dhc/home/main/HomeMissionComponent.kt, presentation/home/src/main/java/com/dhc/home/main/MissionChange.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/276
- MissionCardReRoll 를 onHeightChanged 없이 SubcomposeLayout 으로 미리 높이값 계산해서 배치하는 형태로 리팩토링
- onHeightChanged 없이 구현이 가능했다.
|시연|  
|---|
|<video src="https://github.com/user-attachments/assets/15e5d9af-705c-43ec-ab78-b13dc2a3f372"/>|
기존과 동일하게 동작한다.
close #276
=> [#276] SpendingHabitMissionCard onHeightChanged 함수 없이 개발가능하도록 리팩토링
