- .github/CODEOWNERS
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/22
- CODEOWNERS 를 추가하였습니다.
- 모든파일에 대해 다연/호현/계원이 항상 Reviewers 로 붙도록 세팅하고자합니다.
-
close #22
> [#22] CODEOWNERS 세팅

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/dhc/dhcandroid/BaseViewModel.kt
- app/src/main/java/com/dhc/dhcandroid/MainActivity.kt
- app/src/main/java/com/dhc/dhcandroid/MyApplication.kt
- app/src/main/java/com/dhc/dhcandroid/home/HomeContract.kt
- app/src/main/java/com/dhc/dhcandroid/home/HomeScreen.kt
- app/src/main/java/com/dhc/dhcandroid/home/HomeViewModel.kt
- app/src/main/java/com/dhc/dhcandroid/mvi/EventHandler.kt
- app/src/main/java/com/dhc/dhcandroid/mvi/UiEvent.kt
- app/src/main/java/com/dhc/dhcandroid/mvi/UiSideEffect.kt
- app/src/main/java/com/dhc/dhcandroid/mvi/UiState.kt
- build.gradle.kts
- gradle/libs.versions.toml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/11
> 작업한 내용을 구체적으로 작성해주세요.
- MVI 샘플코드 작성했습니다.
- 간단한 덧뺄셈 기능으로 버튼을 누를 때마다 Toast 메세지가 뜹니다.
- `BaseViewModel`을 중점으로 보면 될 것 같아요!
- 화면에 필요한 상태를 가지고 있는 State, intent전달을 위한 Event, SideEffect로 구성되어 있습니다.
- 많은 채찍과 관심 부탁드립니다~! 개발할 때 참고했던 자료들 첨부 같이하겠습니다.
|MVI Sample|  
|:---|
|<img width="368" alt="스크린샷 2025-04-22 오후 4 22 59" src="https://github.com/user-attachments/assets/0efc567a-6575-4238-89aa-4166d5869c7d" />|
close #11
**Reference**
[A robust MVI with Jetpack Compose](https://proandroiddev.com/a-robust-mvi-with-jetpack-compose-e08882d2c4ff)
[Compose — ViewModel Samples](https://medium.com/@khj1000448/compose-viewmodel-samples-b2e539396c13)
> [#11] MVI Sample Code 및 Base 코드 작성하기

- .github/workflows/generate-aab.yaml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/29
- AAB 파일 자동생성하는 github action 생성
- playstore 에 올리는건 아직 추가 안했슴둥.
- 나중에 심사 맡고나서 자동화 고려해볼까 싶긴한데, 혹시 먼저 해볼 사람 있다면 자유롭게 추가해줘도 무방해용
|AAB 파일 자동생성|
|---|
|![image](https://github.com/user-attachments/assets/c95ec581-57c7-4c24-be0c-8c16ae53dea6)|
close #29
> [#29] AAB 파일 자동생성 github action 생성

- app/src/main/java/com/dhc/dhcandroid/MainActivity.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/Theme.kt
- presentation/intro/src/main/java/com/dhc/intro/intro/IntroScreen.kt
- presentation/intro/src/main/java/com/dhc/intro/splash/SplashScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/97
- 돔황챠 컬러시스템 정의했습니다~!!
- 호현오빠가 말한 시멘틱을 compositionLocal로 사용할 수 있게 했는데...원하던게 이게 맞는지는 봐주세용..
급하게 해서 이방법밖에 생각을 못했는데 더 좋은 방법이 있다면 조언해주시면 감사합니당~!
|:---|---|
|||
close #97
> [#97] 디자인시스템 컬러 정의

- core/designsystem/src/main/kotlin/com/dhc/designsystem/Typography.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/128
- 폰트 추가된 거 작업했어요~!
|:---|---|
|||
close #128
> [#128] 디자인 시스템 컴포넌트 - 폰트 추가

- core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/129
- GradientColor, TransparentColor 가 추가되었어용
- AccentColor, SurfaceColor 는 다 완벽합니당
- 찡끗
- 
close #129
> [#129] 디자인시스템 - 컬러

- core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/badge/DhcBadge.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/badge/model/BadgeType.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/score/DhcScoreText.kt
- core/designsystem/src/main/res/values/strings.xml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/93
- Badge 개발했어용
- 찡끗
|기능 구현|  
|---|
|<img width="419" alt="스크린샷 2025-06-13 오전 12 15 17" src="https://github.com/user-attachments/assets/73a56da1-79d6-49ff-839a-7ee10adb16da" />|
close #93
> [#93] 디자인시스템 컴포넌트 - badge

- core/designsystem/src/main/kotlin/com/dhc/designsystem/DhcSnackBar.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/check/model/DhcCheckStyle.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/134
- 돔황챠 스낵바 만들었어요~!
- 현재는 체크버튼만 들어가는 형태밖에 없긴한데.. 나중에 에러처리일때도 쓸 수 있을 것 같아서 content 받도록 우선 만들어둠~!
-아리가또.
|이것은 스낵바.|
|:---|
|<img width="302" alt="스크린샷 2025-06-13 오후 4 07 13" src="https://github.com/user-attachments/assets/d1e92415-e612-45d6-96fa-63c25d13625c" />|
close #134
> [#134] 디자인 컴포넌트 - 토스트(Feat. 스낵바)

- core/common/build.gradle.kts
- core/common/src/main/java/com/dhc/common/ColorUtil.kt
- core/designsystem/build.gradle.kts
- core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/DhcTipCard.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/DhcTipCardGrid.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/tipcard/TipCardModel.kt
- gradle/libs.versions.toml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/126
- 팁카드 구현완료~!
- 그때 세진이가 서버에서 이미지 받아오자고 했던 것 같아서 우선 Coil 추가해뒀는데 
이부분은 수정사항이 있을 수 있을 것 같아요!
- ui모델을 임시로 만들었는데 icon이나 색상같은걸 API에서 어떻게 줄지에 따라 달라질 것 같아요!
- 아이콘 임시 넣어뒀는데 프리뷰에서는 안뜨네요,,쩝!
|기능A 구현|
|:---|
|<img width="479" alt="스크린샷 2025-06-10 오후 9 46 33" src="https://github.com/user-attachments/assets/7d695308-db65-4993-adb3-6fadb7a10139" />|
close #126
> [#126] 디자인 시스템 컴포넌트 - 팁카드

- core/designsystem/build.gradle.kts
- gradle/libs.versions.toml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/182
- coil 에서 url 기반으로 이미지 받아오려면 okhttp 필요하더라구용..
- 그래서 추가했슴둥
- 찡끗
close #182
> [#182] coil okhttp 라이브러리 추가

- data/src/main/kotlin/com/dhc/dhcandroid/di/NetworkModule.kt
- data/src/main/kotlin/com/dhc/dhcandroid/model/ToggleMissionRequest.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/229
- import 때문에 디버그 오류나요 ㅠㅠ
- 흠.
close #229
> [#229] 디버그 오류 수정

- .github/workflows/build-debug-check.yaml
- .github/workflows/build-release-check.yaml
- .github/workflows/detekt-check.yaml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/232
- 개발 해보았어용,,
- (사실 지금은 테스트중) 
- 흑흑
|기능 구현|
|---|
|![image](https://github.com/user-attachments/assets/bac731f3-5785-4caa-956d-89d43f640bce)|
close #232
> [#232] github action local.properties 대응

- app/src/main/java/com/dhc/dhcandroid/navigation/DhcNavHost.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/badge/DhcBadge.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/badge/model/BadgeLevelType.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/badge/model/BadgeType.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/214
- 뱃지가..컴포넌트 색상이 변경되었어요...
- 레벨타입만 그래도 바뀐거 같아욥
- 디자인팀 혼내주세요ㅋ
|기능A 구현|  
|:---|
|<img width="351" alt="스크린샷 2025-06-25 오후 4 58 18" src="https://github.com/user-attachments/assets/b7bdb937-9ced-4af3-b3a9-b7ef3945741a" />|
close #214
> [#214] 뱃지 컴포넌트 색상 변경

- core/designsystem/src/main/kotlin/com/dhc/designsystem/Color.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/DhcFortuneCard.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/fortunecard/FlippableBox.kt
- core/presentation/src/main/java/com/dhc/presentation/ui/monetaryDetail/MonetaryLuckDetailScreen.kt
- presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
- presentation/intro/src/main/java/com/dhc/intro/fortunecard/IntroFortuneCardScreen.kt
- presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionScreen.kt
- presentation/intro/src/main/res/values/strings.xml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/223
- 인트로 화면 쭉 돌면서 디자인적으로 변경된 요소 열심히 찾아서 바꾸어주었습니다
- 운세카드 이미지 적용건과 카테고리아이템 이미지 적용건은 추후에 작업 예정입니다
- 후우 하아 후우 하아
close #223
> [#223] 인트로 전체적으로 design update

- app/src/main/java/com/dhc/dhcandroid/MainViewModel.kt
- app/src/main/java/com/dhc/dhcandroid/navigation/DhcApp.kt
- data/src/main/kotlin/com/dhc/dhcandroid/datasource/AuthLocalDataSource.kt
- data/src/main/kotlin/com/dhc/dhcandroid/datasource/AuthLocalDataSourceImpl.kt
- data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSource.kt
- data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSourceImpl.kt
- data/src/main/kotlin/com/dhc/dhcandroid/model/MissionCategoriesResponse.kt
- data/src/main/kotlin/com/dhc/dhcandroid/model/UserProfile.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/AuthDataStoreRepository.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/AuthDataStoreRepositoryImpl.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/UserRepository.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/UserRepositoryImpl.kt
- data/src/main/kotlin/com/dhc/dhcandroid/service/DhcService.kt
- data/src/main/proto/user_preferences.proto
- presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryContract.kt
- presentation/intro/src/main/java/com/dhc/intro/category/IntroCategoryViewModel.kt
- presentation/intro/src/main/java/com/dhc/intro/category/model/CategoryItem.kt
- presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/258
- 인트로 회원가입하는 API 도 만들고
- userId 를 Datastore 에 저장하는것도 만들었습니당
- 허허허
close #258
> [#258] 인트로 회원가입 API 투입

- data/src/main/kotlin/com/dhc/dhcandroid/repository/AuthDataStoreRepository.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/AuthDataStoreRepositoryImpl.kt
- presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageRoute.kt
- presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
- presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/AppResetDialog.kt
🔑**이슈 링크**
- https://github.com/mash-up-kr/DHC-Android/issues/287
- https://github.com/mash-up-kr/DHC-Android/issues/291
- 앱 초기화 다이얼로그 박스 제거
- 앱 초기화 관련 동선 오류 수정
close #287
close #291
> [#291] 앱 초기화 관련 수정

- core/designsystem/src/main/kotlin/com/dhc/designsystem/check/DhcCheck.kt
- core/designsystem/src/main/kotlin/com/dhc/designsystem/mission/MissionItemBackGround.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/297
- 체크 클릭 영역 크게~~~ 확인을 위해 백그라운드 잠시 넣음
- 리플 없앳어용
- 뿡
|기능A 구현|  
|:---|
|<img width="233" alt="스크린샷 2025-07-03 오전 11 27 26" src="https://github.com/user-attachments/assets/61a5e37e-3f73-4875-a336-d23d1a2d1320" />|
close #297
> [#297] 체크박스 클릭영역 수정

- data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSource.kt
- data/src/main/kotlin/com/dhc/dhcandroid/datasource/DhcRemoteDataSourceImpl.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt
- data/src/main/kotlin/com/dhc/dhcandroid/service/DhcService.kt
- presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/332
- 앱 초기화시 유저 삭제 api 추가
ㅠㅠ
close #332
> [#332] 초기화 이후 로딩 무한반복 되는 현상 수정

- app/src/main/java/com/dhc/dhcandroid/MainViewModel.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/AuthDataStoreRepository.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/AuthDataStoreRepositoryImpl.kt
- presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageContract.kt
- presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
- presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/MyPageScreen.kt
> User Id 보여지게 추가

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/dhc/dhcandroid/MyApplication.kt
- data/build.gradle.kts
- data/src/main/kotlin/com/dhc/dhcandroid/di/NetworkModule.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/10
아오
|:---|---|
|||
close #
> fix : 플리퍼놈 제거

- .github/workflows/generate-aab.yaml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/341
- generate-aab github action 수정
- local.properties 추가하는 로직을 추가했슴다
- 이제 되겠지..?
|기능 구현|  
|---|
|<img width="932" alt="스크린샷 2025-07-05 오후 6 04 33" src="https://github.com/user-attachments/assets/4b23f1b9-df39-46cb-bfa9-47976a151c89" />|
close #341
> [#341] generate-aab github action 수정

- app/src/main/res/values/strings.xml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/342
- 앱 이름 바꿨어용
- 흠
|스크린샷|
|-|
|<img width="381" alt="image" src="https://github.com/user-attachments/assets/a9c042da-54c3-4bab-a68a-79da7a2ccd09" />|
close #342
> [#342] 앱 이름 변경

- app/build.gradle.kts
- gradle/libs.versions.toml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/10
- 이번엔..통과하자...
|:---|---|
|||
close #
> 버전 코드 후 aab파일 생성!!!

- presentation/intro/src/main/java/com/dhc/intro/mission/IntroMissionScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/348
- 금전운 상세 쪽의 미션 내용 figma 에 맞게 업데이트
- 히히
|Before|After|
|-|-|
|<img width="416" height="936" alt="Image" src="https://github.com/user-attachments/assets/f64b3126-587e-4fea-88ce-0c1f047f12fc" />|<img width="422" height="933" alt="Image" src="https://github.com/user-attachments/assets/28105784-819c-41d8-96df-7e691a67cf8d" />|
close #348
> [#348] Intro Mission 내용 추가

- presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/382
- 호현오빠가 잡아준 버그 수정~!
- 오늘 완료시에는 클릭이벤트 전달 자체를 안하도록 막았습니다~!
(동영상 캡처 잘못해서 옆에 패딩 없어져보이는군,,무시해줘ㅋㅋ)
|기능A 구현|
|:---|
|<video src = "https://github.com/user-attachments/assets/72842643-3d4c-4a50-be97-4daeee6c1278">|
close #382
> [#382] 오늘 미션 전부 끝냈을 시 토스트 안뜨도록 추가

- presentation/home/src/main/java/com/dhc/home/main/HomeScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/379
- 클릭하면 넘어가도록 설정 (이것도 뭔가 다연이가 구현했던 것 같은데,, 컨플릭 처리하면서 날라간 것 같기두)
- 흠
|기능 구현|  
|---|
||
close #379
> [#379] click 시 Event 보내도록 처리

- .github/workflows/auto-release-tag.yaml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/387
- 릴리즈 태그를 매번 만들어주는걸 까먹어서...찾아보니 역시나 방법이 있었슴당
- 근데 테스트는 어케하쥥 main에 머지되면 도는건딩
- https://medium.com/prnd/github%EC%97%90%EC%84%9C-release-tag-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-%EB%A7%8C%EB%93%A4%EC%96%B4-%EC%A3%BC%EA%B8%B0-1%EB%B6%84%EB%A7%8C%EC%97%90-%EC%84%A4%EC%A0%95-5c09a383fb08
참고해서 만들었음!!
|:---|---|
|||
close #387
> 릴리즈 배포 시 자동 태그 되도록 CI 추가

- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/293
- Firebase Crashlytics 적용
|파베 콘솔|
|---|
|<img width="1335" height="303" alt="image" src="https://github.com/user-attachments/assets/8f222c24-57b8-4a3a-8174-b2fa38dda4f6" />|
close #293
> [#293] Firebase Crashlytics 적용

- app/src/main/AndroidManifest.xml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/233
- usesCleartextTraffic 삭제
- https 적용돼서 usesCleartextTraffic 삭제
close #233
> Chore : usesCleartextTraffic 삭제

- app/src/main/java/com/dhc/dhcandroid/navigation/DhcRoute.kt
- presentation/mypage/src/main/kotlin/com/dhc/mypage/ui/MyPageScreen.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/416 // https://github.com/mash-up-kr/DHC-Android/issues/418
- 미션페이지랑 마이페이지 백그라운드 수정~
- 이번엔 누락 안되었으면 좋겠다... ㅠㅠ
|---|---|
|<img width="260" height="576" alt="스크린샷 2025-07-13 오후 11 33 28" src="https://github.com/user-attachments/assets/ca719dc5-5518-46d2-84e0-08d9c6d401c5" />|<img width="260" height="576" alt="스크린샷 2025-07-13 오후 11 37 35" src="https://github.com/user-attachments/assets/81b406f0-f81b-4ec7-b5c5-5f45c7bc8219" />|
|---|---|
|<img width="263" height="576" alt="스크린샷 2025-07-13 오후 11 33 34" src="https://github.com/user-attachments/assets/35e3b27d-dd01-449e-95a7-1a7cdfb10764" />|<img width="258" height="577" alt="스크린샷 2025-07-13 오후 11 51 08" …
> [#416, #418] 미션페이지/마이페이지 백그라운드 수정

- core/designsystem/src/main/kotlin/com/dhc/designsystem/calendar/ui/DhcCalendarDate.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/419
- 미션 현황 - 캘린더 스크롤 안되도록 수정
close #419
> [#419] 미션 현황 - 캘린더 스크롤 안되도록 수정

- data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepository.kt
- data/src/main/kotlin/com/dhc/dhcandroid/repository/DhcRepositoryImpl.kt
- presentation/home/src/main/java/com/dhc/home/HomeViewModel.kt
- presentation/mypage/src/main/kotlin/com/dhc/mypage/MyPageViewModel.kt
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/423
- 앱 초기화 이후 캘린더 캐시 초기화
- 오늘의 미션 끝내기 이후 캐시 초기화
close #432
> [#432] 캘린더 캐시 남아있는 현상 수정

- core/designsystem/src/main/kotlin/com/dhc/designsystem/graph/DhcGraph.kt
- data/src/main/kotlin/com/dhc/dhcandroid/model/AnalysisViewResponse.kt
- presentation/missionstatus/src/main/kotlin/com/dhc/missionstatus/ui/ConsumptionAnalysisUiModel.kt
- presentation/missionstatus/src/main/kotlin/com/dhc/missionstatus/ui/MissionStatusScreen.kt
- presentation/missionstatus/src/main/kotlin/com/dhc/missionstatus/utils/Extensions.kt
- presentation/missionstatus/src/main/res/values/strings.xml
🔑**이슈 링크** : https://github.com/mash-up-kr/DHC-Android/issues/450
|소비 차트|
|---|
|<img width="449" height="495" alt="image" src="https://github.com/user-attachments/assets/cf1c1708-c5c8-4aba-bb01-8891aead5540" />|
close #450
> [#450] 소비 차트로 수정
